name: my_portfolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  battery_plus: ^6.0.3
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  fast_noise: ^2.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  flutter_shaders: ^0.1.3
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.3
  provider: ^6.1.2
  rive: ^0.13.17
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jpg/
    - assets/jpg/about/
    - assets/png/
    - assets/rive/
    - assets/lottie/json/
  # fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #       weight: 400
  #     - asset: assets/fonts/Poppins-SemiBold.ttf
  #       weight: 600
